services:
  artvault:
    image: hanybal87/artvault:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.artvault.rule=Host(`artvault.srv865113.hstgr.cloud`)
      - traefik.http.routers.artvault.entrypoints=websecure
      - traefik.http.routers.artvault.tls=true
      - traefik.http.routers.artvault.tls.certresolver=mytlschallenge
      - traefik.http.services.artvault.loadbalancer.server.port=80
    networks:
      - root_default

networks:
  root_default:
    external: true
